pipeline {
    agent any
    environment {
        CI = 'true'

    }
    stages {
        stage('Build') {
            steps {
                sh 'docker compose run --rm rails bundle exec rails db:chatwoot_prepare'
            }
        }
        stage('Deliver') {
            steps {
              sh 'docker compose up '
                // sh 'docker compose -f docker-compose.production.yaml up '
            }
        }
    }
}